blank_issues_enabled: false
contact_links:
  - name: 💬 Ask a question or get support
    url: https://discord.gg/yourInvite
    about: Join our Discord for general help or discussion.
  - name: 📧 Pro customer support
    url: mailto:pro@renderrides.com
    about: For Pro buyers only — faster, private support.
