name: "✨ Feature Request"
description: Suggest an idea to make AutoCam even better.
title: "[Feature] "
labels: ["feature"]
assignees: []
body:
  - type: markdown
    attributes:
      value: "Thanks for the suggestion! Please fill out the details below."
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      placeholder: "What problem does this feature fix for you?"
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution/workflow
      placeholder: "Describe how you'd like it to work."
  - type: dropdown
    id: tier
    attributes:
      label: Fits which tier?
      options:
        - Core (free)
        - Pro (paid)
        - Not sure
  - type: textarea
    id: refs
    attributes:
      label: References/Inspiration
      placeholder: "Links to videos, screenshots, add-ons…"
